### ISSUE TITLE
cannot infer type for type parameter `S` declared on the struct `MultipartRequest`rustc(E0698)`

### ISSUE THREAD

**Issue by 06chaynes** [cetra3/mpart-async#13]
I am unable to use MultipartRequest inside of an async fn. I was able to reproduce the issue by adding a new function in the hyper examples file and calling the default method.

Rust version: 1.44.1
OS: macOS 10.15.3
mpart-async version: 0.4.1

Code:
```
async fn test() -> Result<(), Error> {
    let mut mpart = MultipartRequest::default();
    Ok(())
}
```

Error:
```
type annotations needed for `mpart_async::client::MultipartRequest<S>`

cannot infer type for type parameter `S` declared on the struct `MultipartRequest`
```

Error when trying to manually build MultipartRequest struct:
```
pub struct MultipartRequest<S>
type inside `async fn` body must be known in this context

cannot infer type for type parameter `S` declared on the struct `MultipartRequest`rustc(E0698)
```

**Comment by cetra3** [comment]
Hi @06chaynes This is because the `MultipartRequest` is generic over the streams submitted to it (which is the `S` parameter).  The hyper example actually constructs a type of `MultipartRequest<FileStream>`.

I.e, the following will work:

```rust
use mpart_async::client::{MultipartRequest};
use mpart_async::filestream::{FileStream};

async fn test() -> Result<(), Error> {
    let mut mpart = MultipartRequest::<FileStream>::default();
    Ok(())
}

```

The compiler will infer the appropriate type for `S` after you use either the `add_file` or `add_stream` function of `MultipartRequest`.  Since you haven't done that in the example, that's why type annotations are needed.

**Comment by 06chaynes** [comment]
Ah thanks, appreciate the help!
